version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mmongia-cloud-resume"
s3_prefix = "mmongia-cloud-resume"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uq4em5paa3i9"
