AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mmongia-cloud-resume

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mmongia-cloud-resume 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH

  VisitorPutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName:  mmongia-cloud-resume
      CodeUri: add_visitor/
      Handler: visitor.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        visitorcount:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visitor
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DynamoDBTable:
    Description: "Dynamo DB"
    Value: !GetAtt DynamoDBTable.Arn
  AddVisitorFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt VisitorPutFunctionRole.Arn
  AddVisitordApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Visitor function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor/"
  AddVisitorFunction:
    Description: "Add Visitor Lambda Function ARN"
    Value: !GetAtt VisitorPutFunction.Arn
  