name: MMongia Cloud Resume

on:
  push:
    branches:
    - cloudresume-aws-stack

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup python
      uses: actions/setup-python@v2
    
    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_SAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SAM_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run AWS SAM Build
      run: sam build --use-container

    - name: Run AWS SAM deploy
      run : sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name mmongia-cloud-resume --s3-bucket ${{ secrets.AWS_SAM_S3_BUCKET }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} 
